# Generated by Django 4.2.6 on 2023-10-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='released',
            field=models.DateTimeField(),
        ),
    ]
